#!/usr/bin/env bash

source ./cluster.conf

gcloud -q compute instances delete $BASE_NODE-1 --zone=$ZONE
gcloud -q compute instances delete $CONTROLLER_NODE-1 --zone=$ZONE

for i in 1 2; do
   gcloud -q compute instances delete $WORKER_NODE-${i} --zone=$ZONE
done

gcloud -q compute firewall-rules delete \
  ingress-deny-all \
  egress-deny-all \
  $VPC_NAME-a-i-internal \
  $VPC_NAME-a-e-internal \
  $VPC_NAME-a-i-external \
  $VPC_NAME-a-e-external 

 gcloud -q compute networks subnets delete $SUBNET_NAME

 gcloud -q compute networks delete $VPC_NAME